# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y4NZ2yMTMldwEDFMmU4iwJVo1OsX3QpZ
"""

# 1. Install required packages
!pip install -q pdfplumber sentence-transformers faiss-cpu gdown

import os
import re
import pickle
import unicodedata
import pdfplumber
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from google.colab import files

# 2. PASTE YOUR SHARE LINK HERE
FOLDER_URL = "https://drive.google.com/drive/folders/1Oaf1Bky0qJdS060IhZECAR2o1hsUljPK?usp=sharing"

# 3. Local Temporary Paths inside Colab
SLIDES_DIR = "/content/slides"
OUTPUT_DIR = "/content/slides_db"
EMBED_MODEL = "all-MiniLM-L6-v2"
NUM_KEYWORDS = 30

# Clear out any old folders and create new ones
!rm -rf {SLIDES_DIR} {OUTPUT_DIR}
os.makedirs(SLIDES_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# 4. Download slides from the share link
print("⏳ Downloading slides from Google Drive link...")
try:
    # gdown will download all PDF files inside the shared folder
    import gdown
    gdown.download_folder(url=FOLDER_URL, output=SLIDES_DIR, quiet=False, use_cookies=False)
except Exception as e:
    print(f"❌ Error downloading: {e}. Make sure link sharing is set to 'Anyone with the link'.")

# 5. Process downloaded files
pdf_files = [f for f in os.listdir(SLIDES_DIR) if f.lower().endswith('.pdf')]

if not pdf_files:
    print(f"⚠️ No PDF files found in downloaded folder. Make sure the folder contains PDF files.")
else:
    print(f"🔍 Found {len(pdf_files)} slide deck(s) to process: {pdf_files}")

    # Initialize embedder
    print("⏳ Loading embedding model...")
    embedder = SentenceTransformer(EMBED_MODEL)

    # Simple text cleaner
    def clean_slide_text(text):
        if not text:
            return ""
        text = unicodedata.normalize("NFKD", text)
        text = text.encode("ascii", "ignore").decode("ascii")
        text = re.sub(r'(\w)-\s*\n\s*(\w)', r'\1\2', text)
        text = re.sub(r"[^\x00-\x7F]+", " ", text)
        text = re.sub(r"\n{2,}", "\n", text)
        text = re.sub(r"[ \t]{2,}", " ", text)
        return text.strip()

    # Clean keyword extraction
    def extract_keywords(text, k=NUM_KEYWORDS):
        try:
            vectorizer = TfidfVectorizer(
                stop_words="english",
                max_features=k,
                ngram_range=(1, 2),
                token_pattern=r'\b[a-zA-Z]{4,}\b',
                lowercase=True
            )
            vectorizer.fit([text])
            return vectorizer.get_feature_names_out().tolist()
        except:
            return []

    # Process each slide deck
    for pdf_file in pdf_files:
        deck_name = os.path.splitext(pdf_file)[0]
        pdf_path = os.path.join(SLIDES_DIR, pdf_file)

        slide_chunks = []
        full_deck_text_buffer = []

        with pdfplumber.open(pdf_path) as pdf:
            for idx, page in enumerate(pdf.pages, start=1):
                text = page.extract_text()
                if not text:
                    continue

                cleaned_text = clean_slide_text(text)
                if cleaned_text:
                    chunk_content = f"[{deck_name} - Slide {idx}] {cleaned_text}"
                    slide_chunks.append(chunk_content)
                    full_deck_text_buffer.append(cleaned_text)

        if slide_chunks:
            full_deck_text = "\n".join(full_deck_text_buffer)
            keywords = extract_keywords(full_deck_text)

            embeddings = embedder.encode(slide_chunks, show_progress_bar=False)
            embeddings = np.array(embeddings).astype("float32")

            index = faiss.IndexFlatL2(embeddings.shape[1])
            index.add(embeddings)

            deck_path = os.path.join(OUTPUT_DIR, deck_name)
            os.makedirs(deck_path, exist_ok=True)

            faiss.write_index(index, os.path.join(deck_path, "index.faiss"))

            with open(os.path.join(deck_path, "texts.pkl"), "wb") as f:
                pickle.dump(slide_chunks, f)

            with open(os.path.join(deck_path, "meta.pkl"), "wb") as f:
                pickle.dump({"chapter": deck_name, "keywords": keywords}, f)

            print(f"✅ Indexed '{deck_name}' with {len(slide_chunks)} slides.")

    print("\n🎉 Slides DB creation complete!")

    # 6. Zip and Download the database back to your computer
    print("⏳ Zipping your slides database for download...")
    !zip -q -r slides_db.zip {OUTPUT_DIR}
    print("👉 Downloading slides_db.zip to your computer...")
    files.download('slides_db.zip')

"""It appears the `Colab_RAG_Project` folder is missing in the path `/content/drive/My Drive/Colab_RAG_Project`, and the `slides` and `slides_db` folders are directly under `/content/drive/My Drive`. Let's correct the `PROJECT_DIR`.

After updating the `PROJECT_DIR`, you can re-run the previous cell (`h39fNMY1NRze`) to ensure the setup proceeds correctly with the right directory structure.
"""